import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { TRPCProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//? Ojo, layout es un nombre reservado y además obliga a usar un export default.Sus props tmb siempre van a tener los children como primera prop(son un React.ReactNode) Fijate que interesante el Readonly<{children: React.ReactNode}> que vino aqui por defecto.Fijate tmb que los files layout.tsx se representarán en la vista en cualquier file de forma descendente(y tmb a los files hermanos, desde ese nivel hacia abajo) en el arbol de files a partir de donde lo ponga (luego este layout pilla a toda la app, pero tmb a page.tsx)
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl={"/"}>
      <html lang="en">
        <body className={inter.className}>
          <TRPCProvider>
            <Toaster />
            {children}
          </TRPCProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
